[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
via_ir = false
evm_version = "cancun"
ffi = true
fs_permissions = [{access = "read-write", path = ".forge-snapshots/"}]

[lint]
exclude_lints = ["screaming-snake-case-immutable", "screaming-snake-case-const"]
lint_on_build = false
